package zeitgeist.common.block;

import net.minecraft.block.Block;
import net.minecraft.block.StepSound;
import net.minecraft.block.material.MapColor;
import net.minecraft.block.material.Material;
import net.minecraft.block.material.MaterialLiquid;
import net.minecraft.item.ItemStack;
import net.minecraft.src.ModLoader;
import zeitgeist.common.zei_Ids;
import zeitgeist.common.item.zei_ItemArch;
import zeitgeist.common.item.zei_ItemComplex;
import zeitgeist.common.item.zei_ItemLumo;
import zeitgeist.common.tile.zei_TileEntityArchitect;
import zeitgeist.common.tile.zei_TileEntityBeacon;
import zeitgeist.common.tile.zei_TileEntityCannon;
import zeitgeist.common.tile.zei_TileEntityLatch;
import zeitgeist.common.tile.zei_TileEntityStatue;
import zeitgeist.common.tile.zei_TileEntityTexBlock;
import zeitgeist.common.tile.zei_TileEntityTexBlock2;
import zeitgeist.common.tile.zei_TileEntityTurn;
import zeitgeist.common.tile.zei_TileEntityWindmill;
import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.common.registry.LanguageRegistry;

public class zei_Blocks {
	public static Block archBend, archBlock;
	public static Block architect, turnBlock, gearbox, miller;
	public static Block chalk, windmill, stoneFigure, plague;
	// public static Block frass = (new
	// zei_BlockFrass(zei_Ids.frass)).setHardness(0.25F).setStepSound(Block.soundGlassFootstep).setBlockName("frass");
	public static Block dapling, boing;
	public static final Material liqui = (new MaterialLiquid(MapColor.waterColor)).setNoPushMobility();
	public static Block plantMass;
	public static Block saltOre, sulfOre;
	public static Block sky, slabBlock, workerBlock, sentryBlock;
	public static final StepSound soundNoFootstep = new StepSound("None", 1.0F, 1.0F);
	public static Block tech, crink;
	public static Block testLiquid, testLiquidStill;
	public static Block texBlock, texBlok, dispBotBlock, latch;
	public static Block toteBlock, beacon, cannon;

	public static void init() {
		tech = (new zei_BlockComplex(zei_Ids.tech)).setHardness(1.0F).setResistance(5F).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("tech");
		crink = (new zei_BlockCrink(zei_Ids.crink, 234)).setHardness(0.1F).setLightOpacity(1).setLightValue(0.5F).setStepSound(Block.soundGlassFootstep).setUnlocalizedName("crink");
		dapling = (new zei_BlockDapling(zei_Ids.dapling)).setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setTextureName("zeitgeist:dapling").setUnlocalizedName("dapling");
		boing = (new zei_BlockBoing(zei_Ids.boing)).setHardness(0.3F).setStepSound(Block.soundGlassFootstep).setUnlocalizedName("boing");
		archBend = (new zei_BlockArchBend(zei_Ids.arch2)).setHardness(0.15F).setStepSound(Block.soundGlassFootstep).setTextureName("zeitgeist:arch2").setUnlocalizedName("arch2");
		archBlock = (new zei_BlockArch(zei_Ids.arch)).setHardness(0.25F).setStepSound(Block.soundGlassFootstep).setUnlocalizedName("arch");
		plantMass = (new zei_BlockPlant(zei_Ids.plantMass)).setHardness(0.5F).setStepSound(Block.soundGrassFootstep).setUnlocalizedName("plantMass");
		sky = (new zei_BlockLumo(zei_Ids.sky)).setHardness(1F).setResistance(5F).setLightValue(1F).setStepSound(Block.soundGlassFootstep).setUnlocalizedName("sky");
		slabBlock = (new zei_BlockSlab(zei_Ids.slabBlock)).setHardness(1.5F).setResistance(10F).setUnlocalizedName("slabBlock");
		workerBlock = (new zei_BlockWorker(zei_Ids.workerBlock)).setHardness(0.5F).setResistance(10F).setUnlocalizedName("workerBlock");
		sentryBlock = (new zei_BlockSentry(zei_Ids.sentryBlock)).setHardness(0.5F).setResistance(10F).setUnlocalizedName("sentryBlock");
		chalk = (new zei_BlockChalk(zei_Ids.chalk, 164)).setHardness(0f).setStepSound(Block.soundPowderFootstep).setUnlocalizedName("chalk");
		windmill = (new zei_BlockWindmill(zei_Ids.windmill, 4, Material.wood)).setHardness(0.5F).setResistance(1F).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("windmill");
		stoneFigure = (new zei_BlockStoneFigure(zei_Ids.stoneFigure)).setUnlocalizedName("stoneFigure");
		plague = (new zei_BlockPlague(zei_Ids.plague)).setUnlocalizedName("plague");
		saltOre = (new zei_BlockOre(zei_Ids.saltOre, 1)).setHardness(3F).setResistance(5F).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("dsltOre");
		sulfOre = (new zei_BlockOre(zei_Ids.sulfOre, 0)).setHardness(3F).setResistance(5F).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("sulfOre");
		architect = (new zei_BlockArchitect(zei_Ids.architect)).setBlockUnbreakable().setStepSound(Block.soundStoneFootstep).setUnlocalizedName("coreMachine");
		turnBlock = (new zei_BlockTurn(zei_Ids.turnBlock)).setHardness(0.05f).setResistance(0).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("turnBlock");
		gearbox = (new zei_BlockGearBox(zei_Ids.gearbox, 10, Material.iron)).setHardness(1F).setResistance(5F).setStepSound(Block.soundMetalFootstep).setUnlocalizedName("gearbox");
		miller = (new zei_BlockMiller(zei_Ids.miller)).setHardness(1F).setResistance(5F).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("miller");
		texBlock = (new zei_BlockTex(zei_Ids.texBlock)).setHardness(0.1F).setResistance(0F).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("texBlock");
		texBlok = (new zei_BlockTex2(zei_Ids.texBlock2)).setHardness(1.5F).setResistance(5F).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("texBlk");
		dispBotBlock = (new zei_BlockDisplayBot(zei_Ids.dispBlock)).setHardness(1.5F).setResistance(5F).setStepSound(Block.soundMetalFootstep).setUnlocalizedName("dispBlock");
		latch = (new zei_BlockLatch(zei_Ids.latchBlock)).setHardness(1F).setResistance(20F).setStepSound(Block.soundMetalFootstep).setUnlocalizedName("latch");
		toteBlock = (new zei_BlockTote(zei_Ids.toteBlock)).setHardness(1F).setResistance(20F).setStepSound(Block.soundMetalFootstep).setUnlocalizedName("toteBlock");
		beacon = (new zei_BlockBeacon(zei_Ids.beaconBlock)).setHardness(1F).setResistance(60F).setStepSound(Block.soundMetalFootstep).setUnlocalizedName("beacon");
		cannon = (new zei_BlockCannon(zei_Ids.cannon)).setHardness(0.8F).setResistance(60F).setStepSound(Block.soundMetalFootstep).setUnlocalizedName("cannon");
		testLiquid = (new zei_BlockFlowing2(zei_Ids.testLiquid, liqui)).setHardness(0.0F).setLightValue(1.0F).setLightOpacity(255).setUnlocalizedName("stuff");
		testLiquidStill = (new zei_BlockStationary2(zei_Ids.testLiquid2, liqui)).setHardness(100F).setLightValue(1.0F).setLightOpacity(255).setUnlocalizedName("stuff");
		GameRegistry.registerBlock(beacon, "Beacon");
		LanguageRegistry.addName(beacon, "Beacon");
		GameRegistry.registerTileEntity(zei_TileEntityBeacon.class, "Beacon");
		GameRegistry.registerBlock(tech, zei_ItemComplex.class);
		ModLoader.registerBlock(crink);
		GameRegistry.registerBlock(archBlock, zei_ItemArch.class, "Architectural Shell");
		LanguageRegistry.addName(archBlock, "Architectural Shell");
		GameRegistry.registerBlock(archBend, "Architectural Connector");
		LanguageRegistry.addName(archBend, "Architectural Connector");
		GameRegistry.registerBlock(boing);
		GameRegistry.registerBlock(dapling);
		GameRegistry.registerBlock(plantMass);
		// ModLoader.registerBlock(frass2);
		GameRegistry.registerBlock(sky, zei_ItemLumo.class);
		GameRegistry.registerBlock(chalk);
		GameRegistry.registerBlock(plague);
		GameRegistry.registerBlock(slabBlock, "Slab");
		LanguageRegistry.addName(slabBlock, "Slab");
		GameRegistry.registerBlock(workerBlock, "workerBlock");
		LanguageRegistry.addName(workerBlock, "workerBlock");
		GameRegistry.registerBlock(sentryBlock, "sentryBlock");
		LanguageRegistry.addName(sentryBlock, "sentryBlock");
		GameRegistry.registerBlock(saltOre, "Salt Ore");
		LanguageRegistry.addName(saltOre, "Salt Ore");
		GameRegistry.registerBlock(sulfOre, "Sulfide");
		LanguageRegistry.addName(sulfOre, "Sulfide");
		GameRegistry.registerBlock(architect, "Architect");
		LanguageRegistry.addName(architect, "Architect");
		GameRegistry.registerTileEntity(zei_TileEntityArchitect.class, "Architect");
		GameRegistry.registerBlock(cannon, "Cannon");
		LanguageRegistry.addName(cannon, "Cannon");
		GameRegistry.registerTileEntity(zei_TileEntityCannon.class, "Cannon");
		GameRegistry.registerBlock(turnBlock, "Shaft");
		GameRegistry.registerTileEntity(zei_TileEntityTurn.class, "Turn");
		LanguageRegistry.addName(turnBlock, "Shaft");
		GameRegistry.registerBlock(stoneFigure, "StoneFigure");
		GameRegistry.registerTileEntity(zei_TileEntityStatue.class, "StoneFigure");
		// ModLoader.registerBlock(mailbox);
		// ModLoader.registerTileEntity(zei_TileEntityMailbox.class, "Mailbox",
		// new zei_TileEntityMailboxRenderer());
		// ModLoader.addName(mailbox, "Mailbox");
		GameRegistry.registerBlock(gearbox, "Gear Box");
		LanguageRegistry.addName(gearbox, "Gear Box");
		GameRegistry.registerBlock(windmill, "Windmill");
		LanguageRegistry.addName(windmill, "Windmill");
		GameRegistry.registerTileEntity(zei_TileEntityWindmill.class, "Windmill");
		GameRegistry.registerBlock(miller, "Miller Stone");
		LanguageRegistry.addName(miller, "Miller Stone");
		GameRegistry.registerBlock(texBlock, "Texture Plate");
		LanguageRegistry.addName(texBlock, "Texture Plate");
		GameRegistry.registerTileEntity(zei_TileEntityTexBlock.class, "TexBlock");
		GameRegistry.registerBlock(texBlok, "Texture Block");
		LanguageRegistry.addName(texBlok, "Texture Block");
		GameRegistry.registerTileEntity(zei_TileEntityTexBlock2.class, "TexBlok");
		GameRegistry.registerBlock(latch, "Latch");
		LanguageRegistry.addName(latch, "Latch");
		GameRegistry.registerTileEntity(zei_TileEntityLatch.class, "Latch");
		GameRegistry.registerBlock(toteBlock, "Tote");
		LanguageRegistry.addName(toteBlock, "Tote");
		GameRegistry.registerBlock(dispBotBlock, "Display Bot Block");
		LanguageRegistry.addName(dispBotBlock, "Display Bot Block");
		GameRegistry.registerBlock(testLiquid, "Liquid");
		LanguageRegistry.addName(testLiquid, "Liquid");
		LanguageRegistry.addName(new ItemStack(tech, 1, 0), "Ancient Construct");
		LanguageRegistry.addName(new ItemStack(tech, 1, 1), "Bionic Mass");
		LanguageRegistry.addName(new ItemStack(tech, 1, 2), "Domestic Tile");
		LanguageRegistry.addName(new ItemStack(tech, 1, 3), "Domestic Tile2");
		LanguageRegistry.addName(new ItemStack(sky, 1, 0), "Atmospheric simulator");
		LanguageRegistry.addName(new ItemStack(sky, 1, 1), "Walkway Tile");
		LanguageRegistry.addName(crink, "Foliage Array");
		LanguageRegistry.addName(boing, "Slider Shell");
		LanguageRegistry.addName(dapling, "Dapling");
		LanguageRegistry.addName(plantMass, "Bionic Stalk");
		// zei_BlockFrass.setAllowed();
	}
}
